- name: Add Node packages to yum
  ansible.builtin.shell: "curl -fsSL https://rpm.nodesource.com/setup_18.x | bash -"



- name: Install Node.js
  ansible.builtin.yum:
    name: nodejs
    state: present

- name: Copy sample app
  ansible.builtin.copy:
    src: files/app.js
    dest: /home/ec2-user/app.js
    owner: ec2-user
    group: ec2-user
    mode: '0755'

- name: Ensure old Node process is stopped
  ansible.builtin.shell: "pkill -f 'node /home/ec2-user/app.js'"
  args:
    warn: false
  failed_when: false


- name: Start sample app
  ansible.builtin.shell: "nohup node /home/ec2-user/app.js &"
  args:
    chdir: /home/ec2-user/

